//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPrestamo
    {
        public int SolicitudID { get; set; }
        public decimal MontoSolicitado { get; set; }
        public decimal TasaInteres { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int EmpleadoID { get; set; }
        public int CuentaID { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
